# Generated by Django 5.2.9 on 2026-01-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_price_snapshot_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='target_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
