# Generated by Django 5.2.9 on 2026-01-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_target_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='target_email',
            new_name='target_email_snapshot',
        ),
    ]
