# Generated by Django 5.2.9 on 2026-02-21 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_rename_target_email_orderitem_target_email_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('tries', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_attempts', to='orders.orderitem')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='fulfillment_status_941c33_idx'), models.Index(fields=['order_item'], name='fulfillment_order_i_4fd599_idx')],
            },
        ),
    ]
