# Generated by Django 5.2.9 on 2026-02-22 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0001_initial'),
        ('orders', '0004_rename_target_email_orderitem_target_email_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='FulfillmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('tries', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('report', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fulfillment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fulfillment.fulfillment')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_items', to='orders.orderitem')),
            ],
        ),
        migrations.DeleteModel(
            name='FulfillmentAttempt',
        ),
        migrations.AddIndex(
            model_name='fulfillmentitem',
            index=models.Index(fields=['status'], name='fulfillment_status_526c43_idx'),
        ),
        migrations.AddIndex(
            model_name='fulfillmentitem',
            index=models.Index(fields=['order_item'], name='fulfillment_order_i_a1f67f_idx'),
        ),
        migrations.AddConstraint(
            model_name='fulfillmentitem',
            constraint=models.UniqueConstraint(fields=('fulfillment', 'order_item'), name='uniq_fulfillment_order_item'),
        ),
    ]
