# Generated by Django 5.2.9 on 2026-02-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0002_fulfillment_fulfillmentitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulfillmentitem',
            name='last_error',
        ),
        migrations.RemoveField(
            model_name='fulfillmentitem',
            name='tries',
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='delivery_email_last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='delivery_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='delivery_email_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='delivery_email_tries',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
