# Generated by Django 5.2.9 on 2026-01-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='target_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
