# Generated by Django 5.2.9 on 2026-01-07 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_rename_target_email_orderitem_target_email_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('zarinpal', 'Zarinpal')], default='zarinpal', max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('redirected', 'Redirected'), ('paid', 'Paid'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('amount_toman', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_rial', models.BigIntegerField()),
                ('authority', models.CharField(blank=True, default='', max_length=64)),
                ('ref_id', models.CharField(blank=True, default='', max_length=64)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('request_response', models.JSONField(blank=True, null=True)),
                ('verify_payload', models.JSONField(blank=True, null=True)),
                ('verify_response', models.JSONField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
            options={
                'indexes': [models.Index(fields=['order', 'status'], name='payments_pa_order_i_a76289_idx'), models.Index(fields=['authority'], name='payments_pa_authori_d17c7e_idx'), models.Index(fields=['ref_id'], name='payments_pa_ref_id_87103e_idx')],
            },
        ),
    ]
