# Generated by Django 5.2.9 on 2026-01-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_onetimecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimecode',
            name='purpose',
            field=models.CharField(choices=[('password_reset', 'Password Reset'), ('email_verify', 'Email Verify')], max_length=30),
        ),
    ]
