# Generated by Django 5.2.9 on 2025-12-28 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(blank=True, default='', max_length=50)),
                ('duration_months', models.PositiveIntegerField()),
                ('delivery_mode', models.CharField(choices=[('activation', 'Activation (personal email)'), ('account', 'Ready account delivery')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'is_active'], name='products_pr_product_ad1dd9_idx')],
                'unique_together': {('product', 'subscription_type', 'duration_months', 'delivery_mode')},
            },
        ),
    ]
