# Generated by Django 5.2.9 on 2025-12-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoption',
            name='price',
        ),
    ]
